let filmesGhibli = [
    {
      titulo: "A Viagem de Chihiro",
      descricao: "Uma jovem segue seus pais para uma casa abandonada, onde eles se transformam em porcos. Chihiro deve encontrar uma maneira de quebrantar o feitiço e libertar seus pais.",
      diretor: "Hayao Miyazaki",
      anoLancamento: 2001,
      genero: "Fantasia",
      duracao: "125 minutos",
      sinopseCompleta: "Chihiro, uma menina de 10 anos, se muda com seus pais para uma nova casa. Ao explorar uma área abandonada, eles encontram um túnel que os leva a um mundo espiritual. Seus pais são transformados em porcos por uma bruxa, e Chihiro deve trabalhar em uma casa de banho para os espíritos para encontrar uma maneira de quebrantar o feitiço e libertar seus pais.",
      imagemPoster: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c4/Spirited_Away_poster.jpg/220px-Spirited_Away_poster.jpg",
      notaIMDB: 8.6,
    },
    {
      titulo: "Meu Vizinho Totoro",
      descricao: "Duas irmãs se mudam para o campo com o pai e descobrem um mundo mágico habitado por criaturas encantadoras, como o Totoro.",
      diretor: "Hayao Miyazaki",
      anoLancamento: 1988,
      genero: "Fantasia",
      duracao: "101 minutos",
      sinopseCompleta: "Satsuki e Mei se mudam com o pai para o campo para ficar mais perto de sua mãe doente, que está em um hospital. Enquanto exploram a nova casa e seus arredores, as meninas descobrem um mundo mágico habitado por criaturas encantadoras, como o Totoro, um espírito da floresta.",
      imagemPoster: "https://upload.wikimedia.org/wikipedia/en/thumb/5/5f/My_Neighbor_Totoro_poster.jpg/220px-My_Neighbor_Totoro_poster.jpg",
      notaIMDB: 8.2,
    },
    {
      titulo: "O Castelo Animado",
      descricao: "Sophie, uma jovem moça, é transformada em uma velha por uma bruxa invejosa. Ela procura a ajuda de um castelo mágico para quebrar o feitiço.",
      diretor: "Hayao Miyazaki",
      anoLancamento: 2004,
      genero: "Fantasia",
      duracao: "124 minutos",
      sinopseCompleta: "Sophie, uma moça de 18 anos, é amaldiçoada por uma Bruxa das Vassouras e transformada em uma velha. Em busca de uma cura, ela se depara com um castelo mágico e seus habitantes, incluindo o misterioso Calcifero.",
      imagemPoster: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b4/Howls_Moving_Castle_poster.jpg/220px-Howls_Moving_Castle_poster.jpg",
      notaIMDB: 8.2,
    },
    {
      titulo: "Princesa Mononoke",
      descricao: "Em um Japão medieval, um jovem príncipe é arrastado para uma guerra entre deuses e homens, lutando para encontrar um equilíbrio entre a natureza e a civilização.",
      diretor: "Hayao Miyazaki",
      anoLancamento: 1997,
      genero: "Aventura, Fantasia",
      duracao: "134 minutos",
      sinopseCompleta: "Ashitaka, um príncipe da tribo Emishi, é amaldiçoado por um deus-javali e precisa encontrar uma cura. Em sua jornada, ele se envolve em uma guerra entre deuses da floresta e humanos que buscam expandir suas terras.",
      imagemPoster: "https://upload.wikimedia.org/wikipedia/en/thumb/c/c9/Princess_Mononoke_poster.jpg/220px-Princess_Mononoke_poster.jpg",
      notaIMDB: 8.4,
    }
  ];